### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Teloyrks** [kurbatov/firmata4j#45]
StandardFirmata is uploaded on my arduino every thing is fine. but when i run the code eclipse shows 
![image](https://user-images.githubusercontent.com/75157062/100495861-b278d800-3179-11eb-8293-ebebe75a1a78.png)
and the creates this .log file
[hs_err_pid7000.log](https://github.com/kurbatov/firmata4j/files/5610157/hs_err_pid7000.log)

**Comment by kurbatov** [comment]
Please, add the following line after `device.start()` and see what happens:

```java
device.ensureInitializationIsDone();
```

**Comment by Teloyrks** [comment]
Still same :(
![image](https://user-images.githubusercontent.com/75157062/100540844-2397b880-326a-11eb-8424-d31b7a9e01c9.png)

**Comment by Teloyrks** [comment]
please help meh !!!!!!!!
please !!!!!
need more info ?

**Comment by kurbatov** [comment]
It looks like a problem with a native part of `jssc` library.

There is one thing you can try with unreleased version of `firmata4j`.

The first step would be cloning this repository and building it locally:

```
$ git clone ggit@github.com:kurbatov/firmata4j.git
$ cd firmata4j
$ mvn install
```

After that you want to modify the `pom.xml` of your project with regard to dependencies to `firmata4j`:

```xml
<dependency>
    <groupId>com.github.kurbatov</groupId>
    <artifactId>firmata4j</artifactId>
    <version>2.3.9-SNAPSHOT</version>
    <exclusions>
        <exclusion>
            <groupId>org.scream3r</groupId>
            <artifactId>jssc</artifactId>
        </exclusion>
     </exclusions>
</dependency>
<dependency>
    <groupId>com.fazecast</groupId>
    <artifactId>jSerialComm</artifactId>
    <version>2.6.2</version>
</dependency>
```

Note that the version of `firmata4j` changes, `jssc` is excluded and a newer `jSerialComm` library is added to the dependencies.

Now, in order to use `jSerialComm` library, modify your code along the following lines:

```java
IODevice device = new FirmataDevice(new JSerialCommTransport("/dev/ttyUSB0"));
device.start();
device.ensureInitializationIsDone();
```

Note that the constructor of `FirmataDevice` should get an instance of `JSerialCommTransport` to use `jSerialComm` library as a transport to the device.

**Comment by Teloyrks** [comment]
thanks. it worked :) <3
